# Generated by Django 5.0.8 on 2024-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=4)),
                ('skills', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
