# Generated by Django 5.0.8 on 2024-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='application',
            name='gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='graduation_year',
            field=models.IntegerField(),
        ),
    ]
