# Generated by Django 5.0.7 on 2024-08-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('job_description', models.TextField()),
            ],
        ),
    ]
